@startuml
actor Пользователь
actor Библиотекарь

Пользователь -- (Искать книгу)
Пользователь -- (Взять книгу на руки)
Пользователь -- (Вернуть книгу)

Библиотекарь -- (Добавить книгу в фонд)
Библиотекарь -- (Списать книгу)
Библиотекарь -- (Искать книгу)
Библиотекарь -- (Взять книгу на руки)
Библиотекарь -- (Вернуть книгу)

@enduml
